[versions]
agp = "8.7.3"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
androidx-activityCompose = "1.9.3"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.2.0"
androidx-core-ktx = "1.15.0"
androidx-espresso-core = "3.6.1"
androidx-lifecycle = "2.8.4"
androidx-material = "1.12.0"
androidx-test-junit = "1.2.1"
appcompat = "1.3.1"
compose-multiplatform = "1.7.0"
core = "1.6.1"
fragmentKtx = "1.8.6"
gson = "2.10.1"
junit = "4.13.2"
kotlin = "2.1.0"
kotlinx-coroutines = "1.10.1"
lifecycleService = "2.8.7"
okhttp = "4.12.0"
screenshot = "1.1.0"
screenshotVersion = "1.1.0-2"
socketIoClient = "4.5.1"
socketIoClientVersion = "2.1.2"
systemHook = "3.8"
uiToolingPreviewAndroid = "1.7.8"
material3Android = "1.3.1"
activityKtx = "1.10.0"
runtimeAndroid = "1.7.8"

[libraries]
androidx-appcompat-v131 = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycleService" }
com-google-code-gson-gson = { module = "com.google.code.gson:gson" }
com-google-code-gson-gson2 = { module = "com.google.code.gson:gson", version.ref = "gson" }
google-gson = { module = "com.google.code.gson:gson" }
gson = { module = "com.google.code.gson:gson" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
michael-winkler-screenshot = { module = "com.github.michael-winkler:Screenshot" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
screenshot = { module = "com.github.michael-winkler:Screenshot", version.ref = "screenshot" }
screenshot-v1102 = { module = "com.github.michael-winkler:Screenshot", version.ref = "screenshotVersion" }
socket-io-client = { module = "io.socket:socket.io-client", version.ref = "socketIoClient" }
socket-io-client-v212 = { module = "io.socket:socket.io-client", version.ref = "socketIoClientVersion" }
system-hook = { module = "lc.kra.system:system-hook", version.ref = "systemHook" }
androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }